In [125]:
from sklearn import ensemble , cross_validation, learning_curve, metrics, preprocessing,tree,neural_network

import numpy as np
import pandas as pd
import xgboost as xgb

In [3]:
data=pd.read_csv("/home/stas/data/mushrooms.csv")

In [4]:
X=data.iloc[:,1:]

In [5]:
y=data.iloc[:,0]

In [6]:
y_new=np.ones(8124)

In [97]:
bank

age            job   marital  education default  balance housing loan  \
0      30     unemployed   married    primary      no     1787      no   no   
1      33       services   married  secondary      no     4789     yes  yes   
2      35     management    single   tertiary      no     1350     yes   no   
3      30     management   married   tertiary      no     1476     yes  yes   
4      59    blue-collar   married  secondary      no        0     yes   no   
5      35     management    single   tertiary      no      747      no   no   
6      36  self-employed   married   tertiary      no      307     yes   no   
7      39     technician   married  secondary      no      147     yes   no   
8      41   entrepreneur   married   tertiary      no      221     yes   no   
9      43       services   married    primary      no      -88     yes  yes   
10     39       services   married  secondary      no     9374     yes   no   
11     43         admin.   married  secondary      no      264     yes   no   
12     36     technician   married   tertiary      no     1109      no   no   
13     20        student    single  secondary      no      502      no   no   
14     31    blue-collar   married  secondary      no      360     yes  yes   
15     40     management   married   tertiary      no      194      no  yes   
16     56     technician   married  secondary      no     4073      no   no   
17     37         admin.    single   tertiary      no     2317     yes   no   
18     25    blue-collar    single    primary      no     -221     yes   no   
19     31       services   married  secondary      no      132      no   no   
20     38     management  divorced    unknown      no        0     yes   no   
21     42     management  divorced   tertiary      no       16      no   no   
22     44       services    single  secondary      no      106      no   no   
23     44   entrepreneur   married  secondary      no       93      no   no   
24     26      housemaid   married   tertiary      no      543      no   no   
25     41     management   married   tertiary      no     5883      no   no   
26     55    blue-collar   married    primary      no      627     yes   no   
27     67        retired   married    unknown      no      696      no   no   
28     56  self-employed   married  secondary      no      784      no  yes   
29     53         admin.   married  secondary      no      105      no  yes   
...   ...            ...       ...        ...     ...      ...     ...  ...   
4491   35    blue-collar    single  secondary      no        0     yes   no   
4492   32     technician    single  secondary      no      309     yes  yes   
4493   28     technician    single   tertiary      no        0     yes   no   
4494   26     technician    single  secondary      no      668     yes   no   
4495   48     management   married   tertiary      no     1175     yes   no   
4496   30    blue-collar    single  secondary      no      363      no   no   
4497   31   entrepreneur    single   tertiary      no       38      no   no   
4498   31     management   married   tertiary      no     1183     yes   no   
4499   45    blue-collar  divorced    primary      no      942      no   no   
4500   38         admin.   married  secondary      no     4196     yes   no   
4501   34     management   married   tertiary      no      297     yes   no   
4502   42       services   married  secondary      no      -91     yes  yes   
4503   60  self-employed   married    primary      no      362      no  yes   
4504   42    blue-collar    single  secondary      no     1080     yes  yes   
4505   32         admin.    single  secondary      no      620     yes   no   
4506   42     unemployed  divorced   tertiary      no     -166      no   no   
4507   33       services   married  secondary      no      288     yes   no   
4508   42         admin.   married    unknown      no      642     yes  yes   
4509   51     technician   married   tertiary      no   

In [8]:
for i in range(0,len(y)):
    if y[i]=="e":
        y_new[i]=0
        
        

In [9]:
estimator = xgb.XGBClassifier(learning_rate=0.01, max_depth=1000, n_estimators=1000, min_child_weight=3)

In [11]:
enc = preprocessing.OneHotEncoder()

In [12]:
bank=pd.read_csv("/home/stas/data/bank.csv",sep=";")

In [13]:
bank

age            job   marital  education default  balance housing loan  \
0      30     unemployed   married    primary      no     1787      no   no   
1      33       services   married  secondary      no     4789     yes  yes   
2      35     management    single   tertiary      no     1350     yes   no   
3      30     management   married   tertiary      no     1476     yes  yes   
4      59    blue-collar   married  secondary      no        0     yes   no   
5      35     management    single   tertiary      no      747      no   no   
6      36  self-employed   married   tertiary      no      307     yes   no   
7      39     technician   married  secondary      no      147     yes   no   
8      41   entrepreneur   married   tertiary      no      221     yes   no   
9      43       services   married    primary      no      -88     yes  yes   
10     39       services   married  secondary      no     9374     yes   no   
11     43         admin.   married  secondary      no      264     yes   no   
12     36     technician   married   tertiary      no     1109      no   no   
13     20        student    single  secondary      no      502      no   no   
14     31    blue-collar   married  secondary      no      360     yes  yes   
15     40     management   married   tertiary      no      194      no  yes   
16     56     technician   married  secondary      no     4073      no   no   
17     37         admin.    single   tertiary      no     2317     yes   no   
18     25    blue-collar    single    primary      no     -221     yes   no   
19     31       services   married  secondary      no      132      no   no   
20     38     management  divorced    unknown      no        0     yes   no   
21     42     management  divorced   tertiary      no       16      no   no   
22     44       services    single  secondary      no      106      no   no   
23     44   entrepreneur   married  secondary      no       93      no   no   
24     26      housemaid   married   tertiary      no      543      no   no   
25     41     management   married   tertiary      no     5883      no   no   
26     55    blue-collar   married    primary      no      627     yes   no   
27     67        retired   married    unknown      no      696      no   no   
28     56  self-employed   married  secondary      no      784      no  yes   
29     53         admin.   married  secondary      no      105      no  yes   
...   ...            ...       ...        ...     ...      ...     ...  ...   
4491   35    blue-collar    single  secondary      no        0     yes   no   
4492   32     technician    single  secondary      no      309     yes  yes   
4493   28     technician    single   tertiary      no        0     yes   no   
4494   26     technician    single  secondary      no      668     yes   no   
4495   48     management   married   tertiary      no     1175     yes   no   
4496   30    blue-collar    single  secondary      no      363      no   no   
4497   31   entrepreneur    single   tertiary      no       38      no   no   
4498   31     management   married   tertiary      no     1183     yes   no   
4499   45    blue-collar  divorced    primary      no      942      no   no   
4500   38         admin.   married  secondary      no     4196     yes   no   
4501   34     management   married   tertiary      no      297     yes   no   
4502   42       services   married  secondary      no      -91     yes  yes   
4503   60  self-employed   married    primary      no      362      no  yes   
4504   42    blue-collar    single  secondary      no     1080     yes  yes   
4505   32         admin.    single  secondary      no      620     yes   no   
4506   42     unemployed  divorced   tertiary      no     -166      no   no   
4507   33       services   married  secondary      no      288     yes   no   
4508   42         admin.   married    unknown      no      642     yes  yes   
4509   51     technician   married   tertiary      no   

In [14]:
le = preprocessing.LabelEncoder()

In [15]:
le.fit(bank['job'])

LabelEncoder()

In [16]:
le.transform(bank['job'])

array([10,  7,  4, ...,  9,  1,  2])

In [34]:
bank_vords=bank.iloc[:,[1,2,3,4,6,7,8,10,15,16]]
bank_numeric=bank.iloc[:,[0,5,9,11,12,13,14]]

In [40]:
X=[]
for i in range(0,10):
    X.append(le.fit_transform(bank_vords.iloc[:,[i]]))

In [66]:
X1=[]
for i in range(0,7):
    X1.append(np.array(bank_numeric.iloc[:,[i]]))

np.array(X1)

In [24]:
y=X[9]

In [31]:
X=X[:9]

In [32]:
len(X)

9

In [44]:
X=np.array(X)

In [58]:
X1

[      age
 0      30
 1      33
 2      35
 3      30
 4      59
 5      35
 6      36
 7      39
 8      41
 9      43
 10     39
 11     43
 12     36
 13     20
 14     31
 15     40
 16     56
 17     37
 18     25
 19     31
 20     38
 21     42
 22     44
 23     44
 24     26
 25     41
 26     55
 27     67
 28     56
 29     53
 ...   ...
 4491   35
 4492   32
 4493   28
 4494   26
 4495   48
 4496   30
 4497   31
 4498   31
 4499   45
 4500   38
 4501   34
 4502   42
 4503   60
 4504   42
 4505   32
 4506   42
 4507   33
 4508   42
 4509   51
 4510   36
 4511   46
 4512   40
 4513   49
 4514   38
 4515   32
 4516   33
 4517   57
 4518   57
 4519   28
 4520   44
 
 [4521 rows x 1 columns],       balance
 0        1787
 1        4789
 2        1350
 3        1476
 4           0
 5         747
 6         307
 7         147
 8         221
 9         -88
 10       9374
 11        264
 12       1109
 13        502
 14        360
 15        194
 16       4073
 17       2317
 18   

In [115]:
%%time
score1.append(cross_validation.cross_val_score(estimator, X.T, y,scoring = 'accuracy', cv = 3))   

CPU times: user 900 ms, sys: 12 ms, total: 912 ms
Wall time: 280 ms


In [53]:
score1=[]

In [116]:
score1

[array([ 0.88992042,  0.88453882,  0.89243028]),
 array([ 0.88992042,  0.88453882,  0.89243028]),
 array([ 0.89171271,  0.88274336,  0.8949115 ,  0.8960177 ,  0.90597345]),
 array([ 0.89171271,  0.88274336,  0.8949115 ,  0.8960177 ,  0.90597345]),
 array([ 0.89171271,  0.88274336,  0.8949115 ,  0.8960177 ,  0.90597345]),
 array([ 0.88741722,  0.90265487,  0.87389381,  0.90707965,  0.89159292,
         0.89823009,  0.89159292,  0.9159292 ,  0.90707965,  0.90486726]),
 array([ 0.89834254,  0.89269912,  0.89269912,  0.89712389,  0.8960177 ]),
 array([ 0.88992042,  0.88453882,  0.89243028])]

In [65]:
len(X.T)

4521

In [64]:
len(X1.T)

AttributeError: 'list' object has no attribute 'T'

In [80]:
X1=np.ones((7,4521),dtype="float64")
for i in range(0,7):
    X1[i]=np.array(bank_numeric.iloc[:,[i]]).T

In [72]:
X1=np.array(X1)

In [84]:
new_X=np.hstack((X.T,X1.T))

In [117]:
%%time
score1.append(cross_validation.cross_val_score(estimator, new_X, y,scoring = 'accuracy', cv = 10))   

CPU times: user 5.13 s, sys: 24 ms, total: 5.15 s
Wall time: 1.36 s


In [103]:
score2=[]

In [101]:
score1[5].mean()

0.89803375725253465

In [110]:
tree_clf=ensemble.RandomForestClassifier(n_estimators=500,max_depth=4000)

In [111]:
%%time
score2.append(cross_validation.cross_val_score(tree_clf, new_X, y,scoring = 'accuracy', cv = 5))   

Exception ignored in: <bound method DMatrix.__del__ of <xgboost.core.DMatrix object at 0x7f285b4100f0>>
Traceback (most recent call last):
  File "/home/stas/anaconda3/lib/python3.6/site-packages/xgboost/core.py", line 324, in __del__
    _check_call(_LIB.XGDMatrixFree(self.handle))
AttributeError: 'DMatrix' object has no attribute 'handle'


CPU times: user 16.2 s, sys: 128 ms, total: 16.3 s
Wall time: 16.3 s


In [114]:
score2[1].mean()

0.89758812888084871

In [118]:
score1

[array([ 0.88992042,  0.88453882,  0.89243028]),
 array([ 0.88992042,  0.88453882,  0.89243028]),
 array([ 0.89171271,  0.88274336,  0.8949115 ,  0.8960177 ,  0.90597345]),
 array([ 0.89171271,  0.88274336,  0.8949115 ,  0.8960177 ,  0.90597345]),
 array([ 0.89171271,  0.88274336,  0.8949115 ,  0.8960177 ,  0.90597345]),
 array([ 0.88741722,  0.90265487,  0.87389381,  0.90707965,  0.89159292,
         0.89823009,  0.89159292,  0.9159292 ,  0.90707965,  0.90486726]),
 array([ 0.89834254,  0.89269912,  0.89269912,  0.89712389,  0.8960177 ]),
 array([ 0.88992042,  0.88453882,  0.89243028]),
 array([ 0.88741722,  0.90265487,  0.87389381,  0.90707965,  0.89159292,
         0.89823009,  0.89159292,  0.9159292 ,  0.90707965,  0.90486726])]

In [123]:
estimator.fit(new_X,y)

XGBClassifier(base_score=0.5, colsample_bylevel=1, colsample_bytree=1,
       gamma=0, learning_rate=0.1, max_delta_step=0, max_depth=5,
       min_child_weight=3, missing=None, n_estimators=50, nthread=-1,
       objective='binary:logistic', reg_alpha=0, reg_lambda=1,
       scale_pos_weight=1, seed=0, silent=True, subsample=1)

In [124]:
estimator.feature_importances_

array([ 0.0387931 ,  0.02047414,  0.02155172,  0.00107759,  0.03340517,
        0.01400862,  0.04956897,  0.11099138,  0.03556034,  0.11530172,
        0.12068965,  0.08297414,  0.24676724,  0.02586207,  0.06573276,
        0.01724138], dtype=float32)

In [129]:
neur=neural_network.MLPClassifier(solver='lbfgs', alpha=1e-5,hidden_layer_sizes=(20, 5), random_state=1)

In [130]:
%%time
score1.append(cross_validation.cross_val_score(neur, new_X, y,scoring = 'accuracy', cv = 5))

CPU times: user 5.38 s, sys: 56 ms, total: 5.44 s
Wall time: 2.73 s


In [131]:
score1

[array([ 0.88992042,  0.88453882,  0.89243028]),
 array([ 0.88992042,  0.88453882,  0.89243028]),
 array([ 0.89171271,  0.88274336,  0.8949115 ,  0.8960177 ,  0.90597345]),
 array([ 0.89171271,  0.88274336,  0.8949115 ,  0.8960177 ,  0.90597345]),
 array([ 0.89171271,  0.88274336,  0.8949115 ,  0.8960177 ,  0.90597345]),
 array([ 0.88741722,  0.90265487,  0.87389381,  0.90707965,  0.89159292,
         0.89823009,  0.89159292,  0.9159292 ,  0.90707965,  0.90486726]),
 array([ 0.89834254,  0.89269912,  0.89269912,  0.89712389,  0.8960177 ]),
 array([ 0.88992042,  0.88453882,  0.89243028]),
 array([ 0.88741722,  0.90265487,  0.87389381,  0.90707965,  0.89159292,
         0.89823009,  0.89159292,  0.9159292 ,  0.90707965,  0.90486726]),
 array([ 0.8839779 ,  0.88495575,  0.88495575,  0.88495575,  0.88495575]),
 array([ 0.8839779 ,  0.88495575,  0.88495575,  0.88495575,  0.88495575])]

In [133]:
poly=preprocessing.PolynomialFeatures(2)

In [134]:
fucking_new_X=poly.fit_transform(new_X)

In [136]:
len(fucking_new_X.T)

153

In [137]:
%%time
score1.append(cross_validation.cross_val_score(estimator, fucking_new_X, y,scoring = 'accuracy', cv = 5))

CPU times: user 16 s, sys: 128 ms, total: 16.1 s
Wall time: 4.26 s


In [142]:
%%time
score1.append(cross_validation.cross_val_score(tree_clf, fucking_new_X, y,scoring = 'accuracy', cv = 5))

CPU times: user 40.7 s, sys: 76 ms, total: 40.7 s
Wall time: 40.7 s


In [144]:
score1[12].mean()-score1[11].mean()

0.0030956338923385784